### ISSUE TITLE
Error trying to add "Soundbox" applet to desktop.

### ISSUE THREAD

**Issue by JillSwift** [collinss/Cinnamon-Soundbox#19]
Using the Cinnamon system settings>applets controls, I downloaded "Soundbox" and then tried to add it to the desktop.
I was met with the error dialog box: "There was a problem loading the selected item, and it has been disabled."

.xsession-errors contains:
>(cinnamon:2903): St-WARNING **: Error parsing stylesheet '/home/yui/.local/share/cinnamon/desklets/soundBox@scollins/2.5/stylesheet.css'; errcode:15

glass.log contains:
>error t=2015-11-04T18:23:27.276Z syntax error
>trace t=2015-11-04T18:23:27.276Z
><----------------
>@/home/yui/.local/share/cinnamon/desklets/soundBox@scollins/2.5/desklet.js:15
>Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:180
>Extension@/usr/share/cinnamon/js/ui/extension.js:138
>loadExtension@/usr/share/cinnamon/js/ui/extension.js:468
>_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203
>---------------->
>error t=2015-11-04T18:23:27.276Z [Desklet "soundBox@scollins"]: Error importing desklet.js from >soundBox@scollins
>error t=2015-11-04T18:23:27.277Z Could not load desklet soundBox@scollins

I have successfully installed and used two other desklets, "desktop caclulator" (also by colinss) and "time and date".

Mint 17.2 amd64
Cinnamon 2.6.13
Linux 3.16.0-38-generic
GPU GeForce GT 630, proprietary drivers 345

Window borders: "Ambiance-Red" from noobslab PPA
Controls: "Ambiance-red" from same PPA

**Comment by collinss** [comment]
This is due to a change in Cinnamon 2.8. The version here on github was fixed a while ago, but I haven't had a chance to upload it to the spices website yet. Until I do, you can download the files from here and put them in ~/.local/share/cinnamon/desklets/soundBox@scollins/.

**Comment by JillSwift** [comment]
Thank you for the response.

I just tried installing from here (downloaded .zip), and I am getting the same set of errors. Also, I'm using Cinnamon 2.6.13

>error t=2015-11-06T06:42:27.389Z No JS module 'soundbox' found in search path
>trace t=2015-11-06T06:42:27.389Z 
><----------------
>@/home/yui/.local/share/cinnamon/desklets/soundBox@scollins/2.5/desklet.js:15
>Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:180
>Extension@/usr/share/cinnamon/js/ui/extension.js:138
>loadExtension@/usr/share/cinnamon/js/ui/extension.js:468
>_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:203
>---------------->
>error t=2015-11-06T06:42:27.389Z [Desklet "soundBox@scollins"]: Error importing desklet.js from soundBox@scollins
>error t=2015-11-06T06:42:27.390Z Could not load desklet soundBox@scollins

**Comment by collinss** [comment]
FYI this is now updated on the spices website as well.
