### ISSUE TITLE
MIssing album covers

### ISSUE THREAD

**Issue by Lito-Frito** [collinss/Cinnamon-Soundbox#22]
I'm using spotify (non-snap version) on Mint 20. It seems that the album covers never load. Tried mucking around with settings (theme, toggling the setting for the cover, etc). No dice.

Overall, really love this spice! Thank you so much for making it. I'll try going through the repo on my end and seeing if I can find a solution. Figured I'd post this here for record keeping purposes

![image](https://user-images.githubusercontent.com/56422761/110027245-baf42800-7cff-11eb-846a-711908cefea3.png)

**Comment by Lito-Frito** [comment]
![image](https://user-images.githubusercontent.com/56422761/110028377-2985b580-7d01-11eb-918e-2e8d4997bdfd.png)


Here's my shot int he dark. Seems like Line 1166 might be the culprit. It seems that trackCover is never set to Show. That or, maybe 1159? Because a variable that might be related is set to False. Honestly, just a shot in the dark.

**Comment by victorinknov** [comment]
Hey @crc8109, did you solve it? I'm with the same error, album covers are not showing up.

**Comment by Lito-Frito** [comment]
> Hey @crc8109, did you solve it? I'm with the same error, album covers are not showing up.

Sorry, no luck. It's been a while but I think toggling what that block of code does didn't help unfortunately.

**Comment by victorinknov** [comment]
Thank you sir! I'll look into it and if I find anything new I'll share. Maybe we can catch something by scouring the commits.

**Comment by collinss** [comment]
I seem to remember something changing about the way album covers get downloaded from spotify. You can check how the cinnamon sound applet does it. Just as an fyi, I haven't been maintaining this desklet for a long time, but you're welcome to submit whatever changes you want to https://github.com/linuxmint/cinnamon-spices-desklets (that's where the most up to date version is anyway). You should probably keep the discussion there anyway.
